# Generated by Django 3.0.4 on 2020-03-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collection_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('collcover', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('typ', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('piececover', models.CharField(max_length=1000)),
                ('Collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.Collection')),
            ],
        ),
    ]
